default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: capacitor
  password: capacitor
  database: capacitor_development
  host: localhost
  port: 5432

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
